=== cinnamonFox/geospatial-rest/src/main/resources/xsd/national-park.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="LatLong">
		<xsd:sequence>
			<xsd:element name="latitude" type="xsd:decimal"></xsd:element>
			<xsd:element name="longitude" type="xsd:decimal"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="NationalPark">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"></xsd:element>
			<xsd:element name="location" type="LatLong"></xsd:element>
			<xsd:element name="status" type="xsd:string"></xsd:element>
			<xsd:element name="state" type="xsd:string"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="parkList">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="national-park" type="NationalPark"
					minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== cinnamonFox/geospatial-rest/src/main/resources/xml/national-park.xml
<?xml version="1.0" encoding="UTF-8"?>

<parkList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../national-park.xsd">
	<national-park>
		<name>Grand Canyon</name>
		<location>
			<latitude>36.056595</latitude>
			<longitude>-112.125092</longitude>
		</location>
		<status>OPEN</status>
		<state>AZ</state>
	</national-park>
	<national-park>
		<name>Yosemite</name>
		<location>
			<latitude>37.865101</latitude>
			<longitude>-119.538330</longitude>
		</location>
		<status>OPEN</status>
		<state>CA</state>
	</national-park>
	<national-park>
		<name>Yellowstone</name>
		<location>
			<latitude>44.423691</latitude>
			<longitude>-110.588516</longitude>
		</location>
		<status>OPEN</status>
		<state>WY</state>
	</national-park>
	<national-park>
		<name>Glacier</name>
		<location>
			<latitude>48.6960847</latitude>
			<longitude>-113.8070624</longitude>
		</location>
		<status>CLOSED</status>
		<state>MT</state>
	</national-park>
	<national-park>
		<name>Denali</name>
		<location>
			<latitude>63.129887</latitude>
			<longitude>-151.197418</longitude>
		</location>
		<status>CLOSED</status>
		<state>AK</state>
	</national-park>
	<national-park>
		<name>Arches</name>
		<location>
			<latitude>38.733082</latitude>
			<longitude>-109.592514</longitude>
		</location>
		<status>OPEN</status>
		<state>UT</state>
	</national-park>
	<national-park>
		<name>Historic Jamestowne</name>
		<location>
			<latitude>37.209722</latitude>
			<longitude>-76.778889</longitude>
		</location>
		<status>OPEN</status>
		<state>VA</state>
	</national-park>
	<national-park>
		<name>Everglades</name>
		<location>
			<latitude>25.286615</latitude>
			<longitude>-80.898651</longitude>
		</location>
		<status>OPEN</status>
		<state>FL</state>
	</national-park>
	<national-park>
		<name>Niagara Falls</name>
		<location>
			<latitude>43.092461</latitude>
			<longitude>-79.047150</longitude>
		</location>
		<status>OPEN</status>
		<state>NY</state>
	</national-park>
</parkList>
